### PR TITLE
Emit diagnostic for unmatched closing delimiter

### LINKED ISSUE #251: Improve diagnostic for only closing paren/bracket
[slide playground](https://yslide.github.io/?input=IwagxglEA&emit-config=N4IgZgTghgxiBcYoBsDOBTANCALgSwFt1UEk0sQATPAN1JQ20vTDwDt0BaKVVPAczb1y2QgAdkeGHhycCAV2Q5hGAL5A&emit-format=pretty&lint=false&parse-only=false&expr-pat=false&shouldExplain=false&explain=)

Given the input

```
1+c)
```

slide emits

<pre><span style="font-weight:bold" class="ansi-bright-red-fg">error[<a href="#slide-output" v-on:click="explain('P0001')">P0001</a>]</span>: <span style="font-weight:bold">Unexpected extra tokens</span>
<span style="font-weight:bold" class="ansi-bright-blue-fg">  |</span>
<span style="font-weight:bold" class="ansi-bright-blue-fg">1 |</span> 1+c) 
<span style="font-weight:bold" class="ansi-bright-blue-fg">  |</span><span style="font-weight:bold" class="ansi-bright-red-fg">    ^</span> <span style="font-weight:bold" class="ansi-bright-red-fg">not connected to a primary statement</span>
<span style="font-weight:bold" class="ansi-bright-blue-fg">  |</span><span style="font-weight:bold" class="ansi-bright-cyan-fg">    -</span> <span style="font-weight:bold" class="ansi-bright-cyan-fg">help</span><span style="font-weight:bold" class="ansi-bright-cyan-fg">: if you meant to specify another statement, add a newline before this token</span>
<span style="font-weight:bold" class="ansi-bright-blue-fg">  |</span></pre>

with the options

```json
{
  "emit_format": "pretty",
  "parse_only": false,
  "expr_pat": false
}
```

on commit e062996b711d55829c1c07637aa8735f9bd90a63.

## Expected result

We can be a little smarter and emit a diagnostic saying that the paren is unmatched.

### PR DESCRIPTION
**Pull request by ayazhafiz**
See the tests and comments for details.

Closes #251

### CODE REVIEW

File: libslide/src/parser.rs [hunk 1]
```diff
@@ -198,6 +188,30 @@ where
...
+    /// `additional_diags` applies additional diagnostic messages to the extra tokens diagnostic,
+    /// if one is produced.
+    fn extra_tokens_diag(&mut self, additional_diags: impl Fn(Diagnostic, Span) -> Diagnostic) {
+        while matches!(self.peek().ty, TT::CloseParen | TT::CloseBracket) {
+            let tok = self.next();
+            self.push_diag(UnmatchedClosingDelimiter!(tok.span, tok.ty));
+        }
+
+        if self.done() {
+            return;
```
Comment (lukebhan) [inline libslide/src/parser.rs:204]: how does this work without a diag getting returned .

**Review by lukebhan — APPROVED** [review]

File: libslide/src/parser.rs [hunk 2]
```diff
@@ -198,6 +188,30 @@ where
...
         node
     }
+
+    /// Creates diagnostics for extra tokens following a primary item.
+    /// All remaining tokens will be consumed in the construction of the diagnostic.
+    ///
+    /// `additional_diags` applies additional diagnostic messages to the extra tokens diagnostic,
+    /// if one is produced.
+    fn extra_tokens_diag(&mut self, additional_diags: impl Fn(Diagnostic, Span) -> Diagnostic) {
+        while matches!(self.peek().ty, TT::CloseParen | TT::CloseBracket) {
```
Comment (lukebhan) [inline libslide/src/parser.rs:198]: i dont understand while if it does match, we push unmatched delim

Comment (ayazhafiz) [reply libslide/src/parser.rs:198]: While we have an unmatched delim, add an error for that.

```
1+ )]) asdasd
   ^ unmatched delim
    ^ unmatched delim
     ^ unmatched delim
       ^^^^^^ extra tokens
```
